= Imprimatur

Imprimatur is a tool for performing automated functional testing on web
applications. The tests are described in a simple test script. Along with the
standard HTTP methods, Imprimatur handles authentication, file uploads and
HTTPS. The responses are validated using regular expressions.

Links:

* http://pythonhosted.org/imprimatur/[User Docs].
* https://github.com/tlocke/imprimatur[Code, bugs, feature requests etc.]


== License

Imprimatur is released under the GPL.


== Regression Tests

To run the regression tests, install http://testrun.org/tox/latest/[tox]:

 pip install tox


then run `tox` from the `imprimatur` directory:

 tox


== Building The Documentation

The docs are written using Asciidoctor. To build them, install asciidoctor:

 apt-get install asciidoctor

Then type:

 asciidoctor docs/index.adoc

and the doc will appear at `docs/index.html`.

== Doing A Release Of Imprimatur

Run `tox` make sure all tests pass, then update the release notes in
`docs/index.adoc` then do:

 asciidoctor docs/index.ado 
 git tag -a x.y.z -m "Version x.y.z"
 python setup.py register sdist bdist_wheel upload upload_docs
